spring:
  application:
    name: BlogFlatformProject
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv23li7WZ2WG4Q1m6XJg
            client-secret: 52314b86b671ad40bff36a4dcc8052a6c0c5d644
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
  web:
    resources:
      static-locations: classpath:/static/

jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012


